#pragma once
#include <string>
// English plain texts encrypted with Vigenere cipher
const std::string test_string1 = "Nm hno eeo anm Okeb, xzl lwftdmxavt wq zhq ggbtbce, wts cuke lrl ieqz, cid ciei au kdpxyflaum. Otrgmqwz, cpz yai xzl Jmpv, tti xvavogtusf vl bsk cayfaxg, hno wrwd gtw cakw, ohy etye ur wckzjzhury! Ok mivlavwk kdpxyilwyk bsk sqelz un auwqv, zl qvpc tti lvziwotk sx doaoum mfgbz mgkrkxzpto. Sk sma lok apirqx suj cyiohijlj bsk huhvlt, pp hrayyoz jlik m qwzyirk fdse anm lttqhasadtgn mkw. Ok klse m hazziyz raev htl hgs iisye jfz gdefakl cksf, eds nqd ransmyy epxe eil kuey un m xsirme uf exguk. Pp huupl anm hglx sx Bxcv-zhq-Wzlkxqulp, sx outj Kazrs, anm aarq wlvxmsuuei. Klk qey wmpd dnqnn ie park i dzrmrv vl ezul, hmwd obd vadehlz esoct rgiulj iaz vwwrqngtq! Xsrk bsk sfeaycij zhmx zhy jpkn flwyk attcq efjomyz tuqwz, gvo jrma flgz eu Emrfh, zpp yemx gm Oaegr, flsa tw wgtqv cpto ngn qzwy xmarioell.";
const std::string test_string2 = "Ni gq oo tv ntf wbls ir Vrvk hhp xamk hlavne, sblhfy uhl zavneaacao pmaazasm, jnzjqdt uhl vdjclwvlw. Tef im cft bsijeiprl iz hau kjlu-zusee bycol, aod pz fie Tecyz Tahez xue npt suk jtt fvozeauivhe! Pnf shl ut cjtf, izf sbr kuff gsocy, aoe tay ce dlby-wcf, iamf h mms tie ayyqlf om Ceuas: tolqf sbr hhp b hblm, Odvk, jtz gqbsvrlgqot. Pplh fie uaifqu-bpx vz ofdbr, yyxfate pne dlbswm ag bsoutq! Ppfn abq mie om cft sfcyyf, migt bj fie uaifqu og lhjut lbzbfu bne rlup puu asf fie nizzastvnlm, mml uhhn Sjlhatye xeot abdpuhh! Zodqatsphs blm oabqs kjnnm, tfrp euxaxee wpnt b svplln qhzspkgf, bsacy zbtjvl ir Vrvk, iofuiog dcxe bvls.";
const std::string test_string3 = "Ogkuz ak bzg mhrv pw yhl tym dghwei, ogkuz acag ca mhv zwcy, mhv bjwzm ow pau ikokpwtz! T mzozvf uaes, ljl irfbweaboe wx jpl tiwgrz, t vzwdgum ffwv-yhoe kpsv zfajpwu h ltfvw yhel! Nqdf inlc wx Nbzacjspkt, Gztyctxs, gmjhlvt fn kvyxnxbz, ubvkcqfi vy tym wzhetvl uqd, Picl-Uqd Gieamp! Nblxiegz lo kidn, wxrwmuv hgd kmjtpulv, ezq vieemv rhlsva ap aae dwmpatiea; ojv wux ewnsl oe bzg oblc-ndcuds, rvv eyhsjmv vox otmsp, aae nqvg zxa, ra xcy ts kpw ubgrzaw; yoh stwmtlw tym oqyed-imykvgs vdwt zxaikzkuz ffz dkmx, ael jghvhvl ta obs jbjguzty Clc-utpzalk aae Wij-Cdty; npg tlltfzwf aae tcdv-jxnkzwu aaak bzg Kxllow flltiwqgk, tnu mkvhulzazgk mhv xjqwxr iqlgz yoi bzg onmrv jcjx! Wyw au aaeim ljhm crv tg jhmgijgk pikp zkt bn bqfisr skilwz, tnu ksp zty cqcg Nblxiegz, 'Bt za A ct mhv sapn'?";

// German plain texts encrypted with Vigenere cipher
const std::string test_string4 = "Lq Aprqbu hvv Tcpngxz, Trumj Hevg Ipzfo zht iht Zfuystrtxor uhv Jiarul wf pyvs grpvvuhr, upsf xy rzflkh mray lrhpk. Xhz bzx, row fq ef mhyjhru Htnxii xdist uaw omewii iahllru Vxrtbrg rizqi Ntlg. Wlv nhmtwe Ttuk xhwtwmrbkmx vxrgkrk Zgyumkie, qxy wzfl zb ayelvboizcsgxu Oihmjt dexox, zvx nxe rbu Xrqd mdn Xkhjk xq vxnr Fpxkh, me see ulxrhysi evg nvfvwvg Wvesi jwiyi.Nhk teefldpl fvomvex utr Ihylrqk utr Cnwmcoi jxcu ehykosj pus –.Whre jiyi evg Imcg lzcevg, niyw hlgcu wlv Xomvsee tukvvtrcngx Zxzopv – jnq aviiw md Weeslr rxj qj srbu. ";
const std::string test_string5 = "Htk Jhgsybnfptpniflqtopob jmcj qa hpx Maxdipyypyarpfto isy Ycoweobhxtuvfzpxnnlckv vr okz Xvjvbbeygtlwp ywjmp ov qic Jigiyqwztckafmzt cah -vulvicavt fptcgde. Hmv ittnngskv Iicykupfkafiwavtwgkzsesxma atk jrm okz Pepyiegsonsvp qiar pov Tiskqzxpdb npwkqai oazpl Sgmhjtmsrmeyiaewear iyzaplwaafiwz ervokv. Qemkq jicjma htk Pniflqtopobrr okz rmyfmyrpt Hrmnnma mx Mmuitsbrbe lmfxrkagiwrb hro jiar xob qic Niryqooxitz lrv Kkqplpt qa ittmz Owgzgiiz lrv gkzzyekbrr Dvzngsk drvrrqplpt. Vhr hkzqiy jqr Ffipfxlhma hpy Orlpougiizmf hfxku htk vbvxgtrr Makuwegjrr rrmvgskz Uepanvkvkqg icymgde. Jme llkcsmrybr Ffipfxlhm qid Mmuitsbrbeka rreyxemnnb qeyt hhq Mkqfttkt qix Qtnvekfgffipfxlhma i. Oomfi Xkbusok qfx zlnrrdokuxwoku jfx tniymmei ka maxdipyydymyrok Brbek jrwztlrvd mcg kpkqtrpz, ermw jqr wegbvweoaplp Gjjitiphrr jme kplcahptma Ffipfxlhmallkcsmrqmvx guv qic fc rvhgzgiyjma Llkcsmrqmvx rkzvrrkz jmcj.";